Repository anuragverma108/SwapReads, pull requests merged in 2024-11, with the labels that each got.

#4340 Fix URL Path for Pricing Section Navigation
  assets/html/about.html
Labels: gssoc-ext, hacktoberfest-accepted

#4350 🛠️FIX : Saved name and other details are not reflection on Profile page
  profiletest.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#4349 Improve feedback section done !
  index.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#4321 fixed the dark mode text of contact us and address line
  assets/css/style.css
Labels: level1, gssoc-ext, hacktoberfest-accepted

#4361 Enhancing the Footer for Better Navigation!
  diverseLiteracy.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#4358 🛠️FIX : Bio input added
  assets/html/profileedit.html
  profiletest.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#4359 Add a Contributing file
  README.md
  contributing.txt
Labels: documentation, level1, gssoc-ext, hacktoberfest-accepted

#4370 🛠️Fix : Home button hover effect problem
  assets/html/profileedit.html
Labels: gssoc-ext, hacktoberfest-accepted

#4374 Improving the navbar !!
  costefficient.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#4393 Sleek and Modern Navbar Update for Improved Usability
  intriguing-mysteries.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#4412 Modified Edit Profile Page
  assets/html/profileedit.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#4411 Improve feedback section done !
  index.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#4409 🛠️Fix : Address edit option added
  address.css
  address.html
  map.jpg
  profiletest.html
Labels: level3, gssoc-ext, hacktoberfest-accepted

#4408 Adjusting the header !!
  historical-chronicals.html
  mindful-living.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#4394 added translator
  assets/html/book_recommend.html
  privacynotice.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#4424 dark mode of about us page doesnt work
  README.md
  assets/html/about.html
  repo_structure.txt
Labels: level2, gssoc-ext, hacktoberfest-accepted

#4371 Footer Enhancement
  assets/css/aboutus.css
  assets/css/style.css
  assets/html/author.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#4427 added dark mode to tips page
  assets/html/tips.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#4418 🛠️ FIX : Wishlist Page added
  book.jpg
  profiletest.html
  wishlist.css
  wishlist.html
  wishlist.js
Labels: level3, gssoc-ext, hacktoberfest-accepted

#4433 Add Project Statistics in Contributors page done !
  contributors/contributor.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#4434 fixing issues in audio book pg and adding popup modal
  README.md
  audiobook.html
  repo_structure.txt
Labels: level2, gssoc-ext, hacktoberfest-accepted

#4453 improved the UI of tips page
  assets/css/style.css
  assets/html/tips.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#4456 Enhanced Card Hover Effect
  assets/html/author.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#4459 🛠️FIX : Author name adding functionality, some animation on input box added
  wishlist.css
  wishlist.html
  wishlist.js
Labels: level2, gssoc-ext, hacktoberfest-accepted

#4306 The text is invisible on Dark mode and the titles are too small in contact section(fixes #4301)
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#4461 link the pricing page
  assets/html/author.html
  assets/html/login.html
  assets/html/tips.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#4463 🛠️FIX: volume control , playback speed of Audio book added
  audiobook.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#4472 🛠️FIX : About Us pages' stats counting
  assets/html/about.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#4466 fixing issues in books page and enhancing footer
  audiobook.html
  books.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#4444 Added book routes following MVC pattern
  controller/book.js
  models/book.js
  routes/books.js
  server.js
Labels: level1, gssoc-ext, hacktoberfest-accepted

#4353 Adding minnify to your whole css and js files improves the performance of the app
  assets/js/fire.js
  assets/js/forgotPassword.js
  assets/js/login.js
  assets/js/signinGoogle.js
  assets/js/signup.js
  chat.js
  contributors/contributor.css
  gulpfile.js
  jsFileEntries.js
  package.json
  webpack.config.js
Labels: level1, gssoc-ext, hacktoberfest-accepted

#4473 Create SECURITY.md
  SECURITY.md
Labels: level1, gssoc-ext, hacktoberfest-accepted

#4467 Add Details and Update the horror page UI
  assets/html/horror.html
  assets/html/top10.html
  horror.html
  index.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#4476 🛠️FIX : Home page User name fetching error
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#4471 Fix top10 page
  assets/html/top10.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#4479 fixing dark mode appearance and header of community page
  README.md
  assets/css/playNow.css
  comsp.html
  repo_structure.txt
Labels: level1, gssoc-ext, hacktoberfest-accepted

#4482 solved #4460 Added quiz for God of small things book
  README.md
  assets/html/god.html
  assets/html/quizzes.html
  repo_structure.txt
Labels: level2, gssoc-ext, hacktoberfest-accepted

#4485 solved #4483
  README.md
  assets/html/maha.html
  assets/html/quizzes.html
  repo_structure.txt
Labels: level2, gssoc-ext, hacktoberfest-accepted

#4489 Fixed homepage visitor counter to track unique visits only once per user session
  assets/js/visitors.js
Labels: level1, gssoc-ext, hacktoberfest-accepted

#4487 Revamp horror page
  assets/html/horror.html
  horror.html
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#4490 Update README.md updated dates of gssoc 2024
  README.md
Labels: documentation, level1, gssoc-ext, hacktoberfest-accepted

#4493 Enhance Card Interaction: Auto-Flip on Hover
  assets/html/tips.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#4492 solved #4491 added quiz to ramayan
  README.md
  assets/html/quizzes.html
  assets/html/ram.html
  repo_structure.txt
Labels: level2, gssoc-ext, hacktoberfest-accepted

#4502 Enhance Card Interaction: Auto-Flip on Hover
  assets/html/author.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#4507 Removed underline and improved hover effects
  sitemap.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#4511 Updated the UI and details of the books pages.
  assets/html/fantasy.html
  assets/html/romance.html
  assets/html/science-fiction.html
  assets/html/suspense-thriller.html
  fantasy.html
  index.html
  romance.html
  science-fiction.html
  suspense-thriller.html
Labels: level3, gssoc-ext, hacktoberfest-accepted

#4514 Dynamic Calendar with Hover Effects
  assets/css/event.css
Labels: level1, gssoc-ext, hacktoberfest-accepted

#4513 🛠️FIX : all page User name fetching error
  Mystical-fantaies.html
  assets/html/ConnReader.html
  assets/html/author.html
  assets/html/book_recommend.html
  assets/html/booking.html
  assets/html/booklistswap.html
  assets/html/bookpref.html
  assets/html/comsp.html
  assets/html/fantasy.html
  assets/html/forgot-pass.html
  assets/html/freeBooks.html
  assets/html/horror.html
  assets/html/login.html
  assets/html/quizzes.html
  assets/html/romance.html
  assets/html/science-fiction.html
  assets/html/suspense-thriller.html
  assets/html/tips.html
  assets/html/top10.html
  biographies.html
  chat.html
  costefficient.html
  environmental-impact.html
  intriguing-mysteries.html
  mindful-living.html
  personalized-reading.html
  romantic-esc.html
  thrilling-adventures.html
Labels: level3, gssoc-ext, hacktoberfest-accepted

#4520 Enhance Card Interaction: Auto-Flip on Hover
  assets/html/top10.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#4516 Fix: Unnecessary text/code displaying on the HOME PAGE.
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#4508 🛠️FIX : ebook and some more page User avatar fetching error
  assets/html/ConnReader.html
  assets/html/book_recommend.html
  assets/html/forgot-pass.html
  assets/html/freeBooks.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#4530 Add books and details to Biography, Self-Help and Historical Fiction
  assets/html/biography.html
  assets/html/historical-fiction.html
  assets/html/self-help.html
  index.html
Labels: level3, gssoc-ext, hacktoberfest-accepted

#4536 fixing dark mode and revamping events page
  README.md
  assets/html/event.html
  repo_structure.txt
Labels: level2, gssoc-ext, hacktoberfest-accepted

#4535 Recreating the Romance Books Page !!
  .vscode/settings.json
  assets/html/romance.html
  assets/images/1984.jpg
  assets/images/Madame Bovary.webp
  assets/images/The Picture of Dorian Gray.jpg
  assets/images/anna_karenina.jpg
  assets/images/beach.jpg
  assets/images/brothers_karamazov.jpg
  assets/images/catcher_in_the_rye.jpg
  assets/images/court.jpg
  assets/images/crime_and_punishment.jpg
  assets/images/dracula.webp
  assets/images/frankenstein.jpg
  assets/images/great-expectations.jpeg
  assets/images/great_gatsby.jpg
  assets/images/hating.jpg
  assets/images/hola.jpg
  assets/images/honey.jpg
  assets/images/itends.jpg
  assets/images/jane_eyre.jpg
  assets/images/kiss.jpg
  assets/images/les.jpg
  assets/images/mebeforeyou.jpg
  assets/images/moby.jpg
  assets/images/notebook.jpeg
  assets/images/odyssey.jpg
  assets/images/outlander.jpg
  assets/images/pride.jpg
  assets/images/red.jpg
  assets/images/rosie.jpg
  assets/images/scarlet.jpg
  assets/images/to_kill_a_mockingbird.png
  assets/images/war.jpeg
  assets/images/wild.jpg
  assets/images/wuthering_heights.jpg
Labels: level2, gssoc-ext, hacktoberfest-accepted

#4537 Create a responsive Contributors page done ! #4533
  contributor/contributorss.css
  contributor/contributorss.html
  contributor/contributorss.js
  contributors/contributor.css
  contributors/contributor.html
  contributors/contributor.js
  index.html
Labels: level3, gssoc-ext, hacktoberfest-accepted

#4547 added peloader as mentioned
  assets/css/style.css
  index.html
  package-lock.json
Labels: level3, gssoc-ext, hacktoberfest-accepted

#4565 🛠️ FIX : Missing mouse pointer effect on Book Wishlist page
  wishlist.css
  wishlist.html
  wishlist.js
Labels: level2, gssoc-ext, hacktoberfest-accepted

#4555 Add Books and details to Non-fiction, Comedy and Detective-fiction.
  README.md
  assets/html/comedy.html
  assets/html/detective-fiction.html
  assets/html/nonfiction.html
  index.html
  repo_structure.txt
Labels: level3, gssoc-ext, hacktoberfest-accepted

#4553 Add Books and details to Poetry, Philosophy and Adventure
  assets/html/adventure.html
  assets/html/fantasy.html
  assets/html/philosophy.html
  assets/html/poetry.html
  index.html
Labels: level3, gssoc-ext, hacktoberfest-accepted

#4569 🛠️ FIX : Missing mouse pointer effect on some page
  address.css
  address.html
  payment.html
  payment.js
Labels: level2, gssoc-ext, hacktoberfest-accepted

#4562 enhancing ui of cards and fixing about us
  README.md
  assets/html/about.html
  index.html
  repo_structure.txt
Labels: level2, gssoc-ext, hacktoberfest-accepted

#4571 🛠️ FIX : Community page carousel autoplay
  comsp.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#4573 ADD Books and details to the genre Fairy-tales, mythology, noir
  assets/html/fairytale.html
  assets/html/mythology.html
  assets/html/noir.html
  index.html
Labels: level3, gssoc-ext, hacktoberfest-accepted

#4577 ADD books and details for the genre True crime, Dystopian and fix Fantasy footer
  assets/html/dystopian.html
  assets/html/fantasy.html
  assets/html/true-crime.html
  index.html
Labels: level3, gssoc-ext, hacktoberfest-accepted

#4500 solved #4499 removed quiz button from navbar
  assets/html/top10.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#4587 Adding the genre pages !!
  assets/html/romance.html
  assets/html/science-fiction.html
  assets/html/suspense-thriller.html
Labels: level3, gssoc-ext, hacktoberfest-accepted

#4586 Add Details and Books of genre Experimental-fiction, satire and Psycological Thriller
  assets/html/experimental-fiction.html
  assets/html/psycological-thriller.html
  assets/html/satire.html
  index.html
Labels: level3, gssoc-ext, hacktoberfest-accepted

#4575 🛠️FIX : Book swapping page User avatar fetching error
  assets/html/booklistswap.html
Labels: gssoc-ext, hacktoberfest-accepted

#4595 added blog section , blogs linked to blog page
  assets/html/blog.html
  index.html
Labels: level3, gssoc-ext, hacktoberfest-accepted

#4551 Add updated font and button size
  assets/css/style.css
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#4590 Fixed small bug and Improved ui of cards in romance.html
  assets/html/author.html
  assets/html/romance.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#4596 adding buttons in genre section of home page
  README.md
  index.html
  repo_structure.txt
Labels: level1, gssoc-ext, hacktoberfest-accepted

#4607 🛠️FIX : Community Chat Page
  assets/html/ConnReader.html
  assets/html/about.html
  assets/html/about1.html
  assets/html/adventure.html
  assets/html/author.html
  assets/html/biography.html
  assets/html/book_recommend.html
  assets/html/booklistswap.html
  assets/html/bookpref.html
  assets/html/classic.html
  assets/html/comedy.html
  assets/html/comsp.html
  assets/html/cyberpunk.html
  assets/html/detective-fiction.html
  assets/html/dystopian.html
  assets/html/experimental-fiction.html
  assets/html/fairytale.html
  assets/html/fantasy.html
  assets/html/forgot-pass.html
  assets/html/freeBooks.html
  assets/html/historical-fiction.html
  assets/html/horror.html
  assets/html/login.html
  assets/html/magical-realism.html
  assets/html/mythology.html
  assets/html/noir.html
  assets/html/nonfiction.html
  assets/html/philosophy.html
  assets/html/poetry.html
  assets/html/psycological-thriller.html
  assets/html/quizzes.html
  assets/html/read_later.html
  assets/html/romance.html
  assets/html/satire.html
  assets/html/science-fiction.html
  assets/html/self-help.html
  assets/html/suspense-thriller.html
  assets/html/tips.html
  assets/html/top10.html
  assets/html/true-crime.html
  assets/html/utopian.html
  biographies.html
  chat.html
  chatt.css
  chatt.html
  chatt.js
  index.html
Labels: level3, gssoc-ext, hacktoberfest-accepted

#4602 Add genre books and details to AUTOBIOGRAPHY
  assets/html/autobiography.html
  index.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#4612 resolved issues
  assets/html/about.html
  assets/html/event.html
  index.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#4626 Enhance Checkout Page
  assets/css/checkout.css
Labels: level1, gssoc-ext, hacktoberfest-accepted

#4641 Enhanced OUR VISION page with Hover Effects
  our-vision.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#4630 Implement Cursor Trail Effect on BOOK Page
  books.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#4634 Add Cursor Trail Effect on Biographies Page
  biographies.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#4639 Cursor Trail Effect on CONNECT WITH SAME Page
  connectWithsame.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#4611 improving pages in profile dropdown
  README.md
  assets/html/profileedit.html
  profiletest.html
  repo_structure.txt
  testp.css
Labels: level3, gssoc-ext, hacktoberfest-accepted

#4540 Fixes#4488
  index.html
  refundpolicy.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#4654 Add details to books of Classic Literature genre and fix the autobiography page issue
  assets/html/classic.html
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#4656 increased the font size of buy now button
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#4628 🛠️ FIX : Missing mouse pointer effect on some page
  assets/css/checkout.css
  assets/html/ConnReader.html
  assets/html/blog.html
  assets/html/booklistswap.html
  assets/html/checkout.html
  assets/html/freeBooks.html
  assets/html/read_later.html
  assets/js/checkout.js
  intriguing-mysteries.html
Labels: level3, gssoc-ext, hacktoberfest-accepted

#4653 improving edit address and recent activity pages
  activity.css
  activity.html
  address.css
  address.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#4671 🛠️FIX : Not working Anchor tags are on event page
  assets/html/event.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#4678 🛠️FIX : Literary Realms carousel's autoplay added
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#4679 added achievements section
  achievements.html
  assets/images/10-books-30-days.png
  assets/images/first-5-read.png
  assets/images/part-of-our-community.png
  assets/images/share-books.png
  assets/images/swap-read-mega-1.png
  assets/images/website-login.png
  assets/images/your-first-read.png
  index.html
  profiletest.html
Labels: level3, gssoc-ext, hacktoberfest-accepted

#4682 rectified the register button in the create new account form
  assets/css/login.css
  assets/html/login.html
Labels: gssoc-ext, hacktoberfest-accepted

#4666 🛠️FIX : Unwanted page removed
  assets/html/about.html
  assets/html/about1.html
  assets/html/autobiography.html
  assets/html/comsp.html
  chat.css
  chat.html
  chat.js
  profile.css
  profile.html
  profiletest.html
  testp.css
Labels: level2, gssoc-ext, hacktoberfest-accepted

#4723 Add PWA (Progressive Web App) done ! #4720
  icon-192x192.png
  icon-512x512.png
  index.html
  manifest.json
  scripts.js
  sw.js
Labels: level2, gssoc-ext, hacktoberfest-accepted

#4736 Page Improvement: Refined User Flow and Updated Aesthetics for Autobiography Books !!
  assets/html/autobiography.html
  assets/images/air.jpeg
  assets/images/bossy.jpeg
  assets/images/castle.png
  assets/images/exp.jpeg
  assets/images/nelson.jpeg
  assets/images/sings.jpeg
  assets/images/stevejobs.jpeg
  assets/images/young.jpeg
Labels: level2, gssoc-ext, hacktoberfest-accepted

#4730 Optimized page Performance and Style for Faster Loading and Better UX !!!
  assets/html/experimental-fiction.html
  assets/images/1.jpg
  assets/images/dict.jpg
  assets/images/fire.jpg
  assets/images/fun.jpg
  assets/images/hss.jpg
  assets/images/naked.jpg
  assets/images/un.jpg
  assets/images/v.jpg
  assets/images/winter.jpg
Labels: level2, gssoc-ext, hacktoberfest-accepted

#4746 improving contributors and badges page
  README.md
  achievements.css
  achievements.html
  contributor/contributorss.css
  contributor/contributorss.html
  repo_structure.txt
Labels: level3, gssoc-ext, hacktoberfest-accepted

#4747 Deleted the book prefer Quiz
  assets/html/ConnReader.html
  assets/html/about.html
  assets/html/author.html
  assets/html/booklistswap.html
  assets/html/freeBooks.html
  assets/html/read_later.html
  assets/html/tips.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#4744 Add inbox page
  assets/html/inbox.html
  index.html
Labels: level3, gssoc-ext, hacktoberfest-accepted

#4750 UI Enhancements for Satire page : Updated Styling and Layout Adjustments
  assets/html/satire.html
  assets/images/animal.jpeg
  assets/images/babb.jpeg
  assets/images/catch22.jpg
  assets/images/dunces.jpeg
  assets/images/five.jpeg
  assets/images/genres/5.jpeg
  assets/images/omens.jpeg
  assets/images/psh.jpeg
  assets/images/sell.jpg
  assets/images/smoke.jpeg
  assets/images/world.jpeg
Labels: level2, gssoc-ext, hacktoberfest-accepted

#4754 enhancing blogs page, improving profile section
  README.md
  activity.html
  assets/css/blog.css
  assets/html/blog.html
  assets/images/genre.jpg
  assets/images/motivation.jpg
  repo_structure.txt
Labels: level2, gssoc-ext, hacktoberfest-accepted

#4756 Enhance BOOKLIST SWAP PAGE
  assets/html/booklistswap.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#4765 add settings page and enhance chat and inbox page
  .vscode/settings.json
  README.md
  activity.html
  assets/css/inbox.css
  assets/css/settings.css
  assets/html/inbox.html
  assets/html/settings.html
  chatt.css
  chatt.html
  index.html
  repo_structure.txt
Labels: level3, gssoc-ext, hacktoberfest-accepted

#4774 enhance terms&cond. and bookListSwap page
  README.md
  assets/html/booklistswap.html
  repo_structure.txt
  terms&cond.html
  terms.css
Labels: level2, gssoc-ext, hacktoberfest-accepted

#4813 UI Revamp: Optimized Navbar and Footer for Consistent Cross-Device Experience
  lol.html
Labels: level3, gssoc-ext, hacktoberfest-accepted

#4817 Update Books page with Image for Improved Design and Engagement
  assets/images/silver.cms
  assets/images/silver.jpg
  books.html
Labels: level3, gssoc-ext, hacktoberfest-accepted

#4819 Added cursor effect , Hover Effect to Chapter Cards with Color Changes and Title Hover Styling !!!
  intriguing-mysteries.html
Labels: level3, gssoc-ext, hacktoberfest-accepted

#4836 Overhaul Chapter Card Content to Provide Thematic Coherence Across Titles Featuring Legends, Love, and Adventure
  lol.html
Labels: level3, gssoc-ext, hacktoberfest-accepted

#4834 Enhance Chapter Card Descriptions for Better Alignment with Inspirational Book Titles and Their Themes
  scifi.html
Labels: level3, gssoc-ext, hacktoberfest-accepted

#4878 Solved issue #4877
  assets/html/freeBooks.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#4873 Fix 404 Page Redirection for Invalid Routes
  .htaccess
  404.html
Labels: level3, gssoc-ext, hacktoberfest-accepted

#4867 Updated the "Quick Links"
  index.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#4889 solved #4887 and #4883 and #4886
  README.md
  assets/html/classic.html
  assets/html/classicq.html
  repo_structure.txt
Labels: level3, gssoc-ext, hacktoberfest-accepted

#4897 solved #4885 #4884 #4891
  README.md
  assets/html/classic.html
  assets/html/classica.html
  assets/html/romance.html
  assets/html/romancea.html
  assets/html/romanceq.html
  repo_structure.txt
Labels: level3, gssoc-ext, hacktoberfest-accepted

#4921 solved #4911 #4912 #4913
  README.md
  assets/html/suspense-thriller.html
  assets/html/suspensea.html
  assets/html/suspenseq.html
  repo_structure.txt
Labels: level3, gssoc-ext, hacktoberfest-accepted

#4872 CREATE CUSTOM ISSUE TEMPLATE
  .github/ISSUE_TEMPLATE/custom.yml
Labels: level1, gssoc-ext, hacktoberfest-accepted

#4925 Enhancing the Classic Literature page !!
  assets/html/classic.html
  diverseLiteracy.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#4871 ADD Q&A Suggestion Template
  .github/ISSUE_TEMPLATE/config.yml
Labels: level1, gssoc-ext, hacktoberfest-accepted

#4931 solved #4926 #4927 #4928
  README.md
  assets/html/science-fiction.html
  assets/html/sciencea.html
  assets/html/scienceq.html
  repo_structure.txt
Labels: level3, gssoc-ext, hacktoberfest-accepted

#4924 Implemented Cursor Trail Effect on INBOX page
  assets/html/inbox.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#4920 Implemented Cursor Trail Effect on SETTINGS page
  assets/html/settings.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#4930 added image to some book recommendations
  README.md
  assets/html/classic.html
  assets/html/romance.html
  repo_structure.txt
Labels: level2, gssoc-ext, hacktoberfest-accepted

#4942 Rate us section button ui fixed
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#4943 solved #4938 #4939 #4940
  README.md
  assets/html/fantasy.html
  assets/html/fantasya.html
  assets/html/fantasyq.html
  repo_structure.txt
Labels: level3, gssoc-ext, hacktoberfest-accepted

#4949 solved #4945 #4946 #4947
  README.md
  assets/html/horror.html
  assets/html/horrora.html
  assets/html/horrorq.html
  repo_structure.txt
Labels: level3, gssoc-ext, hacktoberfest-accepted

#4956 solved #4953 #4954 #4955
  README.md
  assets/html/biography.html
  assets/html/biographya.html
  assets/html/biographyq.html
  repo_structure.txt
Labels: level3, gssoc-ext, hacktoberfest-accepted

#4961 solved #4957 #4958 #4959
  README.md
  assets/html/self-help.html
  assets/html/selfa.html
  assets/html/selfq.html
  repo_structure.txt
Labels: level3, gssoc-ext, hacktoberfest-accepted

#4963 Updated the "Quick Links" again
  index.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#4968 solved #4965 #4966 #4967
  README.md
  assets/html/historical-fiction.html
  assets/html/historya.html
  assets/html/historyq.html
  repo_structure.txt
Labels: level3, gssoc-ext, hacktoberfest-accepted

#4971 💥FIX : Missing Book Quiz link Added
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#4864 Implement Cursor Trail Effect on DONATE BOOKS TO NGO page
  assets/html/ngo.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#4983 quizes styling updated
  assets/html/biographyq.html
  assets/html/classicq.html
  assets/html/fantasyq.html
  assets/html/historyq.html
  assets/html/horrorq.html
  assets/html/romanceq.html
  assets/html/scienceq.html
  assets/html/selfq.html
  assets/html/suspenseq.html
Labels: level3, gssoc-ext, hacktoberfest-accepted

#4952 Enhancing the chat page !!
  chatt.css
  chatt.html
  diverseLiteracy.html
Labels: level3, gssoc-ext, hacktoberfest-accepted

#4987 solved #4984 #4985 #4986
  README.md
  assets/html/poetry.html
  assets/html/poetrya.html
  assets/html/poetryp.html
  repo_structure.txt
Labels: level3, gssoc-ext, hacktoberfest-accepted

#4992 Approach styling updated
  assets/html/biographya.html
  assets/html/classica.html
  assets/html/fantasya.html
  assets/html/historya.html
  assets/html/horrora.html
  assets/html/romancea.html
  assets/html/sciencea.html
  assets/html/selfa.html
  assets/html/suspensea.html
Labels: level3, gssoc-ext, hacktoberfest-accepted

#4977 💥FIX : Unwanted page removed
  cookies.html
  darkmode1.html
  e.css
  e.html
  e.js
  email.css
  email.html
  footer1.css
  footer1.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#4995 solved #4988 #4989 #4990
  README.md
  assets/html/phia.html
  assets/html/philosophy.html
  assets/html/phip.html
  repo_structure.txt
Labels: level3, gssoc-ext, hacktoberfest-accepted

#4933 inline back to top #4932
  assets/html/event.html
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#4892 added functionality to add my blog section
  assets/html/add-your-blog.html
  assets/html/blog.html
Labels: level3, gssoc-ext, hacktoberfest-accepted

#4994 add book recommendation
  book.js
  bookrec.html
  index.html
  styles.css
Labels: level2, gssoc-ext, hacktoberfest-accepted

#4997 solved #4996
  README.md
  assets/html/adv.html
  assets/html/adventure.html
  repo_structure.txt
Labels: level3, gssoc-ext, hacktoberfest-accepted
