Repository anuragverma108/SwapReads, pull requests merged in 2024-07, with the labels that each got.

#2290 Update index.html
  index.html
Labels: gssoc

#2335 Issue #2331
  assets/css/litrary_realms.css
  assets/css/style.css
  assets/css/test-style.css
  index.html
Labels: gssoc, level1

#2307 Visitor Count added
  index.html
Labels: gssoc, level1

#2325 Fixed-hover-efffect-on-card-title
  assets/css/style.css
Labels: gssoc

#2412 Add cost efficient reading page
  costefficient.html
  index.html
Labels: gssoc, level2

#2462 enhance header section dark mode nav kept at right place
  index.html
Labels: gssoc, level1

#2476 Cleared CSS code
  assets/css/BookRecommend.css
  assets/css/style.css
  assets/css/styles.css
Labels: gssoc, level2

#2459 Fixedd the Sign in with google button in login signup
  assets/css/login.css
  assets/html/login.html
Labels: gssoc, level1

#2463 made the books in trending page display 3d
  assets/css/BookRecommend.css
  assets/html/book_recommend.html
Labels: gssoc, level2

#2484 BUG: pricing section height cannot proper
  assets/css/style.css
Labels: gssoc, level1

#2489 Resolved Testimonial Cards
  assets/css/test-style.css
Labels: gssoc, level1

#2492 Added Help Page
  help.html
  index.html
Labels: gssoc, level2

#2497 [BUG]: About Us Navigation cannot proper approach
  assets/css/aboutus.css
  assets/css/style.css
  assets/html/about.html
Labels: gssoc, level1

#2498 Title:- Alignment of realms cards properly
  assets/css/litrary_realms.css
Labels: gssoc, level1

#2503 visitor ui improved
  index.html
Labels: enhancement, good first issue, gssoc, level1

#2504 Enhanced the login page
  assets/css/login.css
  assets/html/login.html
Labels: gssoc, level1

#2508 Theme changer position fixed in read later
  assets/css/read_later.css
  assets/css/style.css
  assets/html/mylogin.html
  assets/html/pricing.html
  assets/html/read_later.html
Labels: gssoc, level1

#2509 Made the backdrop blur in the parivacy notice and added glowing boorders to it
  privacynotice.html
Labels: good first issue, gssoc, level1

#2518 Added three more genres and pictures to free books section
  assets/html/freeBooks.html
  index.html
Labels: gssoc, level1

#2520 HTML and CSS code for social media bar (Issue #2512)
  index.html
Labels: gssoc, level1

#2548 Fixes issue #2531
  assets/css/login.css
  assets/html/login.html
Labels: gssoc, level1

#2570 Added new genre "Satire"
  assets/html/index.html
Labels: gssoc, level1

#2574 Updated booklistswap.html
  assets/html/booklistswap.html
Labels: gssoc, level1

#2590 update login
  assets/html/login.html
Labels: gssoc, level1

#2594 Logout Pop-up added
  index.html
  logout.css
  logout.js
Labels: gssoc, level1

#2622 updating-profile-button-functionality
  index.html
Labels: gssoc, level1

#2623 adding terms and conditions to the website
  Mystical-fantaies.html
  books.html
  historical-chronicals.html
  lol.html
  mindful-living.html
  terms&cond.html
Labels: gssoc, level1

#2625 Implemented a search functionality for searching the books
  books.html
Labels: gssoc, level1

#2678 Alligned Pricing for issue #2677
  assets/css/style.css
  index.html
Labels: gssoc, level1

#2679 Added True Crime Genre.
  index.html
Labels: gssoc, level1

#2681 Aligned backtotop button
  assets/css/style.css
Labels: gssoc, level1

#2694 Added Two new genres
  index.html
Labels: gssoc, level2

#2696 Added Three Unique Genres
  index.html
Labels: enhancement, good first issue, gssoc, level2

#2698 Added Vision of Swap Reads
  index.html
  our-vision.html
Labels: enhancement, gssoc, level3

#2702 Added responsiveness to Literary Realms
  assets/css/litrary_realms.css
  index.html
Labels: gssoc, level2

#2704 added new genre Psychological Thriller
  index.html
Labels: gssoc, level1

#2711 added FAQ section to literary realms pages
  Mystical-fantaies.html
  biographies.html
  historical-chronicals.html
  lol.html
  mindful-living.html
  romantic-esc.html
  scifi.html
  thrilling-adventures.html
Labels: gssoc, level2

#2708 added featured authors
  assets/html/read.html
  assets/images/gr.jpeg
  assets/images/jk.jpeg
  assets/images/mg.jpeg
  assets/images/ne.jpeg
  index.html
Labels: gssoc, level3
