Repository anuragverma108/SwapReads, pull requests merged in 2024-06, with the labels that each got.

#1138 Added underline section and alignment in the Free Book Section
  assets/css/Available.css
  assets/html/freeBooks.html
Labels: gssoc, level1

#1126 Link added to the company logo
  assets/html/index.html
  index.html
Labels: gssoc, level1

#1123 added the booklistswap.html
  assets/html/booklistswap.html
  assets/html/index.html
  index.html
Labels: gssoc, level2

#1106 delete login.js
  assets/js/login.js
Labels: gssoc, level1

#1100 Stiffpixels bug cursor and alignment
  assets/css/style.css
  index.html
Labels: gssoc, level1

#1099 Solved issue 972
  assets/css/style.css
Labels: bug, gssoc, level1

#1096 hover the social media icons
  index.html
Labels: gssoc, level1

#1067 footer is changed and hover the social media icons
  index.html
Labels: gssoc, level2

#1092 The numbering pattern of the cards "Explore Different Genres" was made uniform.
  index.html
Labels: gssoc, level1

#1152 cookie feature added
  index.html
Labels: gssoc, level2

#1150 Solving issue #1131-"Book Exchange Hub" Form Fix
  assets/css/style.css
  index.html
Labels: gssoc, level1

#1147 Adding icons in contact page
  assets/css/style.css
  index.html
Labels: gssoc, level1

#1008 Solved issue due to drop-down menu.
  assets/css/login.css
  assets/html/login.html
Labels: gssoc, level2

#1077 Fixing Issue #451 - Nothing linked to literary realms
  .vscode/settings.json
  assets/images/genres/1.jpg
  assets/images/genres/10.jpg
  assets/images/genres/2.jpg
  assets/images/genres/3.jpg
  assets/images/genres/4.jpg
  assets/images/genres/5.jpeg
  assets/images/genres/6.jpg
  assets/images/genres/7.jpg
  assets/images/genres/8.jpg
  assets/images/genres/9.jpg
  assets/images/genres/auth1.jpg
  assets/images/genres/auth2.jpg
  assets/images/genres/auth3.jpg
  assets/images/genres/c1.jpg
  books.html
  index.html
Labels: gssoc, level1

#1162 Update Readmore
  index.html
Labels: gssoc, level1

#1201 Added styling to Google translator
  assets/css/style.css
Labels: gssoc, level1

#1200 Added hovering effect to social media icons
  index.html
Labels: gssoc, level1

#1198 Feat: Add a Button to Login/signup wIth GOOGLE #1084
  assets/css/login.css
  assets/html/mylogin.html
Labels: gssoc, level1

#1197 In both index.html file path corrected to redirect to respective pages
  assets/html/login.html
Labels: gssoc, level2

#1195 Update freeBooks.html
  assets/html/freeBooks.html
Labels: gssoc, level1

#1192 Fixed the typo in the Book Exchange Hub Section
  index.html
Labels: gssoc, level1

#1177 Solved issue 1007
  assets/css/style.css
  index.html
Labels: gssoc, level1

#1191 Added the Navbar in Book recommendation Page
  assets/html/book_recommend.html
Labels: gssoc, level1

#1185 Connect with the Reader button is in centre.
  assets/css/style.css
Labels: gssoc, level1

#1181 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: gssoc

#1273 Duplicate index.html Removed with no Problems in paths in Navbar
  assets/html/forgot-pass.html
  assets/html/login.html
  assets/html/mylogin.html
  index.html
Labels: gssoc, level3

#1205 Fixed Alligment of text in book Exchange box
  assets/css/style.css
  index.html
Labels: gssoc, level1

#1213 Removed the collision of backToTop and chatBot buttons !!
  assets/css/style.css
Labels: gssoc, level1

#1229 cards-bg-color modified
  index.html
Labels: gssoc, level1

#1276 Improved Aboutus page
  assets/css/style.css
  assets/html/about.html
Labels: gssoc, level1

#1307 hrefs issue solved and added footer
  assets/html/about.html
Labels: gssoc, level1

#1302 Login Ajust in MObile Devices
  assets/css/login.css
  assets/css/style.css
Labels: gssoc, level1

#1310 Updated login.html
  assets/css/login.css
  assets/html/login.html
Labels: gssoc, level1

#1321 Improved The Address and it's detail color
  index.html
Labels: gssoc, level1

#1376 issue number #1243
  index.html
Labels: gssoc, level1

#1375 footer updated
  index.html
Labels: gssoc, level1

#1374 Map margin-bottom added
  index.html
Labels: gssoc, level1

#1373 About us page is not responive
  assets/css/aboutus.css
  assets/css/forgot-pass.css
Labels: gssoc, level1

#1377 added hover
  assets/css/style.css
  index.html
Labels: gssoc, level1

#1365 footer of aboutus page fixed
  assets/css/preloader.css
  assets/css/style.css
  assets/html/about.html
  assets/html/booklistswap.html
Labels: gssoc, level1

#1359 Added style to back to top icon and Made the X icon visible on dark mode
  assets/css/style.css
  index.html
Labels: gssoc, level1

#1356 fixed login.html footer links
  assets/html/login.html
Labels: gssoc, level1

#1352 fixed login signup broken functionality
  assets/html/login.html
  assets/html/mylogin.html
  assets/js/login.js
  assets/js/signup.js
Labels: gssoc, level1

#1378 Added font color in dark theme
  index.html
Labels: gssoc, level1

#1339 no double times footer
  assets/html/index.html
Labels: gssoc, level1

#1334 Corrected navbar Padding
  index.html
Labels: gssoc, level1

#1326 Made contribution section in about us page
  assets/css/about.css
  assets/css/contributor.css
  assets/html/about1.html
  assets/js/contribute.js
  index.html
Labels: gssoc, level1

#1325 Unique Testimonials for Improved User Experience
  assets/images/testimonials-5.jpg
  assets/images/testimonials-6.jpg
  index.html
Labels: gssoc

#1319 Made changes to card UI
  assets/css/style.css
Labels: gssoc, level1

#1317 Adjust TOOGLE in NAVBar
  assets/css/style.css
Labels: gssoc, level1

#1299 feat: added automated thankyou email
  assets/css/style.css
  assets/html/index.html
  assets/js/script.js
  index.html
  package-lock.json
  package.json
  server.js
Labels: gssoc, level1

#1387 Fixed Nav-bar
  index.html
Labels: gssoc, level1

#1388 Solved issue 1348
  assets/css/style.css
  index.html
Labels: gssoc, level1

#1390 Contact Send Now issue solved updated
  index.html
Labels: gssoc, level1

#1395 Solved issue 1178
  assets/css/style.css
  assets/css/test-style.css
  index.html
Labels: gssoc, level1

#1396 Heading fix and centerized with adequate padding
  assets/css/style.css
  assets/html/index.html
Labels: gssoc, level1

#1398 Fixed Faq- section with enough margin & Bg color
  assets/html/index.html
  books.html
  index.html
Labels: gssoc, level1

#1411 fixed dropdown element
  assets/css/aboutus.css
  assets/css/style.css
Labels: gssoc, level1

#1440 Added our contributors section
  assets/html/about.html
  index.html
Labels: gssoc, level1

#1445 Add hover color to buttons in the cookie section
  index.html
Labels: gssoc, level1

#1446 Enhance Footer Social Icons in Home Page
  assets/css/style.css
  index.html
Labels: gssoc, level1

#1451 Enhance Login Page
  assets/css/login.css
  assets/html/login.html
Labels: gssoc, level1

#1492 Added the github icon
  index.html
Labels: gssoc, level1

#1494 changed fav icon color
  books.html
Labels: gssoc, level1

#1468 Successfully added Hover effect to the cookies
  index.html
Labels: gssoc, level1

#1543 "implement Modal Pop-ups for "copyright policy and Privacy policy"
  index.html
  modals(privacy policy).css
Labels: gssoc, level2

#1496 Added Quick links in E book Also
  assets/html/freeBooks.html
Labels: gssoc, level1

#1565 Removed duplicate form in newsletter
  index.html
Labels: help wanted, gssoc, level1

#1582 Update index.html - Recommendation page
  index.html
Labels: gssoc, level1

#1585 Update index.html
  index.html
Labels: gssoc

#1589 Solved issue 1559
  assets/css/style.css
Labels: gssoc, level1

#1462 Changed the twitter Icon to X in Login Page
  assets/html/login.html
Labels: gssoc, level1

#1529 Create LICENSE
  LICENSE
Labels: gssoc, level1

#1499 Remove Duplicate Email Input for Newsletter Subscription
  index.html
Labels: gssoc, level1

#1547 Added a "READ LATER" webpage
  assets/css/Available.css
  assets/css/read_later.css
  assets/css/style.css
  assets/html/about.html
  assets/html/book_recommend.html
  assets/html/booklistswap.html
  assets/html/forgot-pass.html
  assets/html/freeBooks.html
  assets/html/index.html
  assets/html/login.html
  assets/html/mylogin.html
  assets/html/read_later.html
  assets/js/freeBooks.js
  assets/js/read_later.js
  books.html
  index.html
Labels: gssoc, level2

#1567 Added favicon on About page
  assets/css/aboutus.css
  assets/html/about.html
Labels: gssoc, level1

#1577 removed cursor effect
  index.html
Labels: gssoc, level2

#1579 Read More Hover Effect Added
  index.html
Labels: gssoc, level1

#1587 Resolved navbar links directing issue on free e-books page
  assets/html/freeBooks.html
Labels: good first issue, gssoc, level1

#1596 Enhanced Footer of Books Page
  assets/html/freeBooks.html
Labels: gssoc, level1

#1599 Implemented check over message length
  index.html
Labels: gssoc, level1

#1620 FIXED Broken Redirect Links
  assets/html/about.html
  assets/html/book_recommend.html
  assets/html/booklistswap.html
  assets/html/freeBooks.html
  assets/html/login.html
Labels: gssoc, level1

#1621 done #1427
  index.html
Labels: gssoc, level1

#1636 Overlapping icon on login and sign-up page fixed
  assets/css/login.css
Labels: gssoc, level1

#1638 Change the button
  assets/css/Available.css
  package-lock.json
Labels: gssoc, level1

#1659 made cookie button functional and visible
  index.html
Labels: gssoc, level1

#1678 Added New Styles.css
  assets/css/styles.css
  index.html
Labels: gssoc, level2

#1698 Update index.html
  index.html
Labels: gssoc, level2

#1699 Bug resolved: Long Navbar in literary realms
  assets/css/style.css
  assets/html/literaryrealms.html
Labels: gssoc, level1

#1700 Updated dark mode progress bar color
  scrollbar.css
Labels: gssoc

#1704 Adding hovering effect over rating stars
  assets/js/rateUsModal.js
Labels: gssoc, level1

#1709 Solved issue 1694
  assets/css/style.css
Labels: good first issue, gssoc

#1711 Updated About us and home page
  assets/css/style.css
  assets/html/about.html
  assets/html/about1.html
  index.html
Labels: gssoc, level1

#1721 Removed double hover effect
  assets/css/login.css
  assets/css/style.css
  assets/html/login.html
Labels: gssoc, level2

#1731 Remove Duplicate Newsletter Subscription and enhance footer of freeBooks Page
  assets/html/freeBooks.html
Labels: gssoc, level1

#1732 navbar is sticked in webpage
  assets/css/test-style.css
Labels: gssoc

#1740 fixed text not visible in dark mode
  assets/html/about.html
Labels: gssoc, level1

#1741 Fix: Resolved conflicts: HTML JS fixed for learn more in cookie modal
  assets/css/styles.css
  index.html
Labels: gssoc, level1

#1778 Removed the unnecessary black circles from 4 pages.
  assets/html/book_recommend.html
  assets/html/freeBooks.html
  assets/html/index.html
  assets/html/login.html
Labels: gssoc, level1

#1798 Icons are Aligned
  assets/html/login.html
Labels: gssoc

#1751 Cookie buttons are avaliable
  index.html
Labels: gssoc, level1

#1756 Toggle position
  assets/css/styles.css
  assets/html/about.html
  assets/html/book_recommend.html
  assets/html/booklistswap.html
  assets/html/login.html
  index.html
Labels: gssoc, level2

#1759 Fixed the toggle buttons
  assets/css/style.css
Labels: gssoc, level1

#1784 added the color to the instructions list in dark mode
  assets/css/login.css
Labels: gssoc, level1

#1786 Fixed the visibility issue of certain elements of the page
  assets/css/aboutus.css
  assets/html/about.html
Labels: gssoc, level1

#1797 Added github icon to footer and removed duplicates
  assets/css/style.css
  index.html
Labels: gssoc, level1

#1810 Validation for Book Excahnge Hub and enhanced ui for rate us Modal
  assets/css/style.css
  index.html
  package-lock.json
Labels: gssoc, level2

#1811 disappeared navbar on scrolling
  assets/css/style.css
  index.html
Labels: gssoc, level1

#1824 remove unnecessary styling for email input, completes #1813
  assets/css/style.css
Labels: gssoc, level1

#1827 fixed background of email in footer and functioning of back to top button in free e books webpage
  assets/css/style.css
  assets/html/freeBooks.html
Labels: gssoc, level1

#1829 Double icon and subscribe newslater
  assets/html/freeBooks.html
  assets/html/index.html
  assets/html/literaryrealms.html
  assets/html/login.html
  assets/html/read_later.html
  books.html
  index.html
Labels: gssoc, level1

#1832 Added the maxLength feature and corrected css
  assets/css/style.css
  index.html
Labels: gssoc, level1

#1849 Added linkedin icon to the footer
  assets/css/aboutus.css
  assets/html/about.html
  assets/html/about1.html
Labels: gssoc, level1

#1855 Added the blue color for like.
  books.html
Labels: gssoc, level1

#1859 Corrected the footer of login/signup page
  assets/html/login.html
Labels: gssoc, level1

#1897 Faviconfix
  assets/html/addremovebook.html
  assets/html/booklistswap.html
  assets/html/read_later.html
Labels: gssoc, level1

#1878 Navbar Duplicate content Removed from Free Ebook Section
  assets/html/freeBooks.html
Labels: gssoc, level1

#1895 update cookie
  assets/css/styles.css
  index.html
Labels: gssoc, level1

#1889 Update CARDS CSS
  assets/css/style.css
Labels: enhancement, gssoc, level2

#1910 Added author filter in book recommendation
  .vscode/settings.json
  assets/css/BookRecommend.css
  assets/html/book_recommend.html
  index.html
Labels: enhancement, gssoc, level2

#1936 make the footer social icon transition faster
  assets/css/style.css
Labels: gssoc

#1911 fixed the problem of dark mode not working in few pages
  assets/html/about1.html
  assets/html/book_recommend.html
  assets/html/freeBooks.html
  assets/html/index.html
  assets/html/literaryrealms.html
  assets/html/login.html
  assets/html/pricing.html
  assets/html/read_later.html
Labels: gssoc, level1

#1919 Fixed copyright policy and private notice in dark mode of home page and login/signup page and added copyright policy and private notice for about us page .
  assets/css/about.css
  assets/css/aboutus.css
  assets/css/style.css
  assets/html/about.html
  modals(privacy policy).css
Labels: gssoc, level1

#1934 e
  e.css
  e.html
  e.js
Labels: gssoc, level1

#1941 user section
  assets/css/style.css
  assets/images/avatar.jpg
  assets/images/edit profile.jpg
  assets/images/help.png
  assets/images/inbox.png
  assets/images/logout.png
  assets/images/settings.png
  assets/images/user.jpg
  index.html
Labels: gssoc, level2

#1961 update buy now button
  assets/css/style.css
Labels: gssoc, level1

#1970 nav bar hover color is no good in dark mode can we change this in to cream color
  assets/css/style.css
  assets/css/styles.css
Labels: gssoc

#1973 Title fixed on two pages
  assets/html/freeBooks.html
  assets/html/pricing.html
Labels: gssoc

#1999 Feat : Added thrilling adventures page
  assets/css/Available.css
  thrilling-adventures.html
Labels: gssoc, level2

#2024 Fixed navbar hover effect
  assets/css/style.css
Labels: gssoc

#2088 Corrected the dark mode problem
  books.html
  index.html
Labels: gssoc, level1

#2090 Feat/laugh out loud , added a complete new page of comedy books under laugh out loud section .
  index.html
  lol.html
Labels: level2

#2102 Solved Dublicate Book Exchange Hub #2101
  assets/css/style.css
  index.html
Labels: gssoc, level1

#2147 added tilty effect using vanilla.js
  assets/html/about.html
Labels: gssoc, level1

#2193 #2180 login page
  assets/js/login.js
  assets/js/script.js
Labels: gssoc, level3

#2207 Rate us Section Updated
  assets/css/rate.css
  assets/html/rate.html
  assets/images/emoji/emoji-1.png
  assets/images/emoji/emoji-2.png
  assets/images/emoji/emoji-3.png
  assets/images/emoji/emoji-4.png
  assets/images/emoji/emoji-5.png
Labels: gssoc, level1

#2210 fix:footer-free-e-book
  assets/html/freeBooks.html
Labels: bug, gssoc, level1

#2219 Navbar on the about us page is properly visible .
  assets/css/aboutus.css
  assets/css/style.css
  assets/html/about.html
Labels: gssoc, level1

#2245 added the backend format for contact
  .hintrc
  assets/validation/validate.schema.js
  assets/validation/zodschema.js
  index.html
  package-lock.json
  package.json
  server.js
Labels: gssoc, level1

#2249 Adjust the position of cards in pricising and fixed the positiuon of copyright policy and privacy notice and made it visible in dark mode
  assets/css/Available.css
  assets/css/style.css
Labels: gssoc, level1

#2246 change in html h2 section-title
  index.html
Labels: gssoc

#2252 Changes done in style.css in button
  assets/css/style.css
Labels: question
