Repository anuragverma108/SwapReads, pull requests merged in 2024-08, with the labels that each got.

#2729 Added zoom option when hovering over an donate books options
  index.html
Labels: gssoc, level1

#2719 fixed the three translate , top and chat icon
  assets/css/style.css
Labels: gssoc, level1

#2745 Enhanced Rate Us Page
  assets/css/rate.css
  assets/js/rate.js
  index.html
Labels: gssoc, level2

#2748 Added Memoir genre
  assets/html/index.html
Labels: gssoc, level1

#2760 Modified Navbar alignment
  index.html
Labels: gssoc, level2

#2768 Altered Sizes of cards
  costefficient.html
  environmental-impact.html
Labels: gssoc, level1

#2792 remove-extra-space
  assets/css/style.css
Labels: gssoc

#2780 Added Event Calender
  assets/html/event.html
  index.html
Labels: gssoc, level2

#2816 Added 2 more question and answer in FAQ Section
  assets/html/index.html
Labels: gssoc, level1

#2829 Solved issue 2799
  index.html
Labels: gssoc
