Repository anuragverma108/SwapReads, pull requests merged in 2024-05, with the labels that each got.

#13 Pricing card border issue fixed | #12
  assets/css/style.css
  index.html
Labels: enhancement, GSSoC24

#10 sharp border fixed issue#1
  assets/css/style.css
Labels: good first issue, GSSoC24

#26 Commit by Sahil Tyagi after changing UI
  login.css
  login.html
Labels: enhancement, GSSoC24

#65 bug fix footer link, fixes #61
  index.html
Labels: bug, GSSOC24, Level 1

#63 Fix: Bookchange Hub responsive
  assets/css/style.css
  index.html
Labels: GSSOC24, Level 1

#84 feat: added issue btns and respective forms
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/documentation.yml
  .github/ISSUE_TEMPLATE/feature.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  assets/css/style.css
Labels: documentation, GSSOC24, Level 1

#91 In response to the issue #32 Missing Social Media Handles Links
  index.html
Labels: good first issue, GSSOC24, Level 1

#93 #90 changed the text to cross Button
  assets/images/close.png
  login.css
  login.html
Labels: good first issue, GSSOC24, Level 1

#103 Fixes #89 : Now all fields are required to fill and specific datatypes are only allowed.
  assets/js/script.js
  index.html
Labels: good first issue, gssoc, Level 1

#127 Added a rate us page
  index.html
  rate.html
Labels: enhancement, gssoc, level1

#131 In response to Issue #31 Missing video in the Hero Section
  index.html
Labels: gssoc, level1

#164 Home page title added
  index.html
Labels: gssoc

#195 Change the style of Alert box.
  assets/js/script.js
  index.html
Labels: enhancement, good first issue, gssoc, level1

#198 fix/Hover effect color on navbar's elements are not properly aligned.…
  assets/css/style.css
Labels: good first issue, gssoc, level1

#202 New twitter icon
  index.html
Labels: good first issue, gssoc, level1

#235 adding currency chosing option under #77 issue
  index.html
Labels: good first issue, gssoc, level1

#228 Added Zod Validation to the Project to User Signin and Signup endpoints
  package-lock.json
  package.json
  server.js
  validation/validate.schema.js
  validation/zodschema.js
Labels: enhancement, gssoc, level2

#297 footer responsiveness fixed
  assets/css/style.css
Labels: gssoc, level2

#300 Added Free E-Books Section
  index.html
Labels: enhancement, good first issue, gssoc, level3

#298 login page fixed
  assets/css/login.css
  assets/html/login.html
Labels: enhancement, gssoc, level2

#278 Add scroll to top button
  assets/css/style.css
  assets/js/scroll.js
  index.html
Labels: gssoc, level2

#286 Updated colour in dark mode
  assets/css/style.css
Labels: gssoc, level1

#293 added hover animation to the connect button of exchange form
  assets/css/style.css
  index.html
  package-lock.json
Labels: gssoc, level2

#365 Added Rate us link in footer
  index.html
Labels: enhancement, good first issue, gssoc, level1

#410 enhance authentication functions with error handling and feedbac
  assets/js/login.js
  assets/js/scroll.js
Labels: enhancement, gssoc, level1

#424 DOC: added table of contents and featured in section
  .github/assets/gssoc24.png
  README.md
Labels: good first issue, gssoc, level1

#423 email filter added
  assets/html/login.html
Labels: bug, gssoc, level2

#416 FEAT: Adding a ChatBot Assistant #400
  index.html
Labels: enhancement, gssoc, level3

#428 Fixes #260 Adjusted the currency input field border.
  assets/css/style.css
Labels: bug, gssoc, level1

#432 Footer Updated
  assets/css/socialmedia.css
  assets/css/style.css
  assets/images/FB icon.png
  assets/images/YT icon.png
  assets/images/insta icon.png
  assets/images/twitter-icon.png
  index.html
Labels: enhancement, gssoc, level2

#446 Fixing Issue #418 - Contact Form Does Not Check Email Validity and String Lengths
  assets/css/style.css
  assets/js/script.js
  index.html
Labels: gssoc, level2

#477 Fixed : Validation added in signup and login page
  assets/css/login.css
  assets/html/login.html
Labels: enhancement, good first issue, gssoc, level1

#462 Improvised ChatBot Assistant #400
  index.html
Labels: gssoc, level3

#458 Fixed logout issue
  index.html
Labels: gssoc, level2

#437 fixed twitter logo
  index.html
Labels: gssoc, level2

#490 feat/google auth
  assets/css/login.css
  assets/html/login.html
Labels: gssoc, level2

#504 remove link on play icon at index page
  index.html
Labels: gssoc, level1

#496 Added the Dark Mode Icon
  assets/css/style.css
  index.html
Labels: gssoc, level2

#501 Update button, footer for 'Create Account', 'rights reserved'.
  assets/css/login.css
  assets/html/login.html
Labels: gssoc, level1

#497 Fix: Made FAQ section responsive
  assets/css/style.css
Labels: gssoc, level2

#518 Update registration/login message and button text color
  assets/css/login.css
  assets/html/login.html
Labels: gssoc, level1

#532 Testimonials
  assets/css/test-style.css
Labels: gssoc, level2

#538 Fix: Made text on testimonials appear when flipping.
  assets/css/test-style.css
Labels: gssoc, level2

#642 Fixes #489
  assets/css/style.css
  index.html
Labels: gssoc, level2

#675 Fixed #302, Added alerts for invalid input in price field
  index.html
Labels: gssoc, level1

#658 navbar and pricing modified
  assets/css/style.css
  assets/css/test-style.css
Labels: enhancement, gssoc

#693 #649 Added Back to Top SVG
  assets/css/style.css
  index.html
Labels: invalid, gssoc

#698 fixed navbar and hero section
  assets/css/style.css
  index.html
Labels: good first issue, gssoc, level1

#618 Bug issue for "Rate Us" in dark mode is Fixed.
  assets/css/style.css
  assets/js/rateUsModal.js
  index.html
Labels: bug, enhancement, gssoc, level1

#734 added workflow as mentioned in issue #718
  .github/workflows/autocomment-iss-close.yml
Labels: gssoc, level1

#739 Fix #705: Simplified the navbar
  assets/css/style.css
  index.html
Labels: gssoc, level2

#752 added workflow as mentioned in issue #
  .github/workflows/autocomment-pr-raise.yml
Labels: gssoc, level2

#754 Adjusted Heights of Cards and hover effect
  assets/css/test-style.css
Labels: gssoc, level1

#770 Navbar hover improved
  assets/css/style.css
Labels: gssoc, level1

#790 improve hover effect
  assets/css/style.css
  index.html
Labels: level2

#792 Background Themes fixed
  assets/css/style.css
Labels: gssoc, level1

#802 Added eye symbol and it's functionality
  assets/css/addremove.css
  assets/html/addremovebook.html
Labels: enhancement, gssoc, level1

#805 Enhance Styling for Requirements List in login page
  assets/css/login.css
Labels: gssoc, level1

#812 Solved back-to-top and chatbot overlapping
  assets/css/style.css
Labels: bug, enhancement, help wanted, gssoc, level2

#813 fixed the schema to register users
  assets/validation/zodschema.js
  mylogin.html
Labels: gssoc, level2

#816 Enhance Logo Visibility in Bright Mode
  assets/css/style.css
Labels: gssoc, level1

#818 switch-alingment-css
  assets/css/style.css
Labels: gssoc, level1

#823 add hover on email box radius
  assets/css/style.css
  index.html
Labels: gssoc, level1

#828 FIx : Change UI of Reset Password Page #817
  assets/css/forgot-pass.css
  assets/html/forgot-pass.html
Labels: gssoc, level2

#587 Removed the extra subject and message box
  index.html
Labels: duplicate, wontfix

#829 added the transition on benefits cards
  assets/css/style.css
Labels: gssoc, level2

#845 book_recommend
  assets/css/style.css
  book_recommend.html
  index.html
Labels: enhancement, gssoc, level3

#839 changed the social media icons size in footer
  assets/css/style.css
  index.html
Labels: enhancement, gssoc, level1

#842 Fix : Issue #820
  assets/css/style.css
Labels: enhancement, gssoc, level2

#843 [BUG] : Responsive Issue fixed
  assets/css/style.css
  assets/css/test-style.css
Labels: bug, gssoc, level2

#847 swapreads chatbot updated
  index.html
Labels: enhancement, gssoc, level2

#853 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: good first issue, gssoc, level1

#856 Created LICENSE file
  LICENSE
Labels: gssoc, level1

#859 Update README.md
  README.md
Labels: gssoc, level2

#875 fixed the style for booktitle label in Book Exchange Hub form
  index.html
Labels: gssoc, level1

#909 Documentation Update: Correct Typo Errors in Pull Request Checklist #902
  .github/Pull_Request_Template.md
  assets/css/Available.css
  index.html
Labels: documentation, gssoc, level1

#912 "Add Free E-Books Section and CSS Styling"
  assets/css/Available.css
  index.html
Labels: gssoc, level3

#914 Remove the bug of "Text on 'Subscribe' button becomes invisible on ho…
  assets/css/style.css
Labels: gssoc, level1

#928 RateUs Updated Accoring to Need of Text and Icons
  assets/html/index.html
  assets/html/rate.html
Labels: gssoc, level1

#970 Solved genres card issue
  assets/css/style.css
Labels: bug, gssoc, level2

#958 Backend_Mail_Validation
  assets/validation/validate.schema.js
  assets/validation/zodschema.js
  package-lock.json
  package.json
  server.js
Labels: gssoc, level2

#936 enhanced the login page
  assets/css/login.css
  mylogin.html
Labels: gssoc, level2

#941 Corrected Grammatical error in "Some Frequently Asked Questions"
  index.html
Labels: gssoc, level1

#942 Added description in the sign up feature of "Your Booklist For Shopping"
  assets/html/addremovebook.html
Labels: gssoc

#947 Added reset password connection
  assets/html/forgot-pass.html
  assets/js/fire.js
  assets/js/forgotPassword.js
Labels: bug, enhancement, gssoc, level2

#978 Made Login page and Forgot password page responsive
  assets/css/forgot-pass.css
  assets/css/login.css
  assets/css/style.css
  assets/html/login.html
Labels: gssoc, level2

#984 solved issue 973
  index.html
Labels: documentation, gssoc

#985 improved the hero image so now it covers better
  assets/css/style.css
Labels: bug, gssoc, level1

#999 Solves issue #945 loader animation
  assets/css/preloader.css
  assets/css/style.css
  assets/html/addremovebook.html
  assets/html/forgot-pass.html
  assets/html/freeBooks.html
  assets/html/index.html
  assets/html/login.html
  assets/js/fire.js
  book_recommend.html
  index.html
Labels: enhancement, gssoc, level2

#997 Visibility Issue in Benefits Section Resolved
  assets/css/style.css
Labels: gssoc, level1

#990 swiper button
  index.html
Labels: bug, gssoc, level1

#1005 Changed height of navbar
  assets/css/style.css
Labels: gssoc, level1

#1040 Fixed the alignment of Send Now button
  assets/css/style.css
  index.html
Labels: gssoc, level1

#1047 Changed color of forgot passowrd
  assets/css/login.css
Labels: gssoc, level1

#1049 Code restructure issue solve
  assets/html/index.html
  index.html
Labels: gssoc, level1

#1050 Stiffpixels feature responsive hero section
  assets/css/style.css
  index.html
Labels: gssoc, level2

#1055 Design and Implement Register Page Frontend with Responsive Navbar and Login Page Enhancements
  assets/css/login.css
  assets/html/login.html
  assets/html/mylogin.html
Labels: gssoc, level2

#1001 Bug Fixed: Overflowing Mobile Design
  assets/css/style.css
Labels: gssoc, level1

#1002 [Fixes]: Testimony Card Swiper not working correctly #915
  assets/css/test-style.css
  index.html
Labels: gssoc, level2

#1080 Update Login.html
  assets/html/login.html
Labels: gssoc, level1

#1064 fixed the line-break issue
  assets/css/style.css
Labels: gssoc, level2
