Repository anuragverma108/SwapReads, pull requests merged in 2024-10, with the labels that each got.

#2876 removed unknown bar present in the home page
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#2869 fixed Dark mode icon is not properly arrange in login section
  assets/html/login.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#2904 #2860 Added special exception handling of preventing special characters which lead to client side injection attacks
  assets/html/login.html
Labels: level1, gssoc-ext

#2905 fixed alignment and spacing
  index.html
Labels: level1, gssoc-ext

#2909 Fixed some Issues and added new page
  diverseLiteracy.html
  index.html
Labels: level2, gssoc-ext

#2911 Fixed #2910 : added CODE OF CONDUCT file
  CODE_OF_CONDUCT.md
Labels: level2, gssoc-ext

#2912 i have fixed logout box and display and the navbar padding and spacing
  index.html
  logout.css
Labels: level1, gssoc-ext

#2916 Button padding fix issue#2915
  assets/html/freeBooks.html
Labels: level1, gssoc-ext

#2917 Dropdown Icon in the Frequently Asked Questions Section
  assets/css/style.css
Labels: level1, gssoc-ext

#2920 Fix #2878: Fixed Navbar Bug
  assets/css/MenuClick.css
  assets/css/style.css
  index.html
Labels: level1, gssoc-ext

#2925 too much spaces fixed
  assets/css/style.css
Labels: level1, gssoc-ext

#2928 icons overlapping problem is resolved
  index.html
Labels: level1, gssoc-ext

#2938 add links in side icon
  index.html
Labels: level1, gssoc-ext

#2942 Fixed text overlap issue
  assets/css/style.css
Labels: level1, gssoc-ext

#2947 fixed collapsing icons in footer
  index.html
Labels: level1, gssoc-ext

#2948 logout Style
  logout.css
Labels: level1, gssoc-ext

#2949 readibility issues fixed
  assets/css/style.css
  index.html
Labels: level1, gssoc-ext

#2954 refresher refresh on click fix #2863
  assets/js/refresher.js
Labels: level1, gssoc-ext

#2950 footer section icons in homepage
  index.html
Labels: level1, gssoc-ext

#2913 Alignment of Contact-Us and Address section Updated
  index.html
Labels: level1, gssoc-ext

#2953 discord added
  Mystical-fantaies.html
  assets/css/MenuClick.css
  assets/css/read_later.css
  assets/css/style.css
  assets/css/styles.css
  assets/css/test-style.css
  assets/font-6/css/all.css
  assets/font-6/css/brands.css
  assets/html/ConnReader.html
  assets/html/about.html
  assets/html/about1.html
  assets/html/book_recommend.html
  assets/html/booklistswap.html
  assets/html/comsp.html
  assets/html/freeBooks.html
  assets/html/index.html
  assets/html/login.html
  assets/html/mylogin.html
  assets/html/pricing.html
  assets/html/read_later.html
  biographies.html
  books.html
  chat.html
  comsp.html
  copyrightpolicy.html
  costefficient.html
  diverseLiteracy.html
  environmental-impact.html
  historical-chronicals.html
  index.html
  intriguing-mysteries.html
  lol.html
  mindful-living.html
  our-vision.html
  privacynotice.html
  profile.css
  romantic-esc.html
Labels: level1, gssoc-ext

#2960 Shifted navbar so that it is in center
  index.html
Labels: level1, gssoc-ext

#2964 ISSUE #2963: Added SwapReads logo in the footer
  index.html
Labels: level1, gssoc-ext

#2976 Did proper allignment in footer section
  index.html
Labels: level1, gssoc-ext

#2978 Update mylogin.html (#2973)
  mylogin.html
Labels: level1, gssoc-ext

#2982 image in contact us was compress and was looking bad now it is …
  index.html
Labels: level1, gssoc-ext

#2985 address div is now align properly
  index.html
Labels: level1, gssoc-ext

#2989 changed the font size in html\login.html
  assets/html/login.html
Labels: level1, gssoc-ext

#2993 Added padding and margin in about page
  .vscode/settings.json
  assets/css/aboutus.css
Labels: level1, gssoc-ext

#2994 FIXED THE SOCIAL HANDLE ISSUE
  index.html
Labels: level1, gssoc-ext

#2998 Fixed sidebar background on smaller screens for better readability
  assets/css/aboutus.css
Labels: level2, gssoc-ext

#3004 Fix: Responsive Iframe for Smaller Devices
  assets/css/style.css
  assets/html/about.html
Labels: level2, gssoc-ext

#3006 Fixed Navbar Profile Icon Behaviour which was going down with page
  assets/css/style.css
  comsp.html
Labels: level1, gssoc-ext

#3007 icon issue fixed
  SwapReads/assets/images/ctc2.png
  index.html
Labels: level1, gssoc-ext

#2987 Add: Responsiveness #2919
  assets/css/style.css
  index.html
Labels: level2, gssoc-ext

#3025 FIXED THE CONTACT SECTION IN THE PAGE
  assets/css/style.css
  index.html
Labels: enhancement, level1, gssoc-ext, hacktoberfest-accepted

#2996 Fix Bugs on Get in Touch Section
  assets/css/style.css
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#3015 Issue for mobile response was fixed
  index.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#3016 Worked on the Minor Bug #3012
  assets/css/login.css
Labels: level1, gssoc-ext, hacktoberfest-accepted

#3021 help.html(3018)
  help.html(#3018)
Labels: level2, gssoc-ext, hacktoberfest-accepted

#3027 Enhance UI of Contact Section: Adjust Map Size and Address Box Height
  assets/css/style.css
  index.html
  server.js
Labels: level2, gssoc-ext, hacktoberfest-accepted

#3028 fixed hover effect timing of social media icons
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#3034 fixed inconsitent nav bar throughout home and community spotlight
  assets/html/comsp.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#3038 I've successfully added the new Stay connected portion along with a perfect email box so that the reader gets understood what it is actually and can register there by writing their email
  email.css
  email.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#3045 Fixed issue #3043: Overlapping of the address section with the Get in Touch Section
  index.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#3049 Worked on Bug #3046
  assets/css/style.css
Labels: level1, gssoc-ext, hacktoberfest-accepted

#3052 Fixed Bugs
  help.html
  privacynotice.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#3022 Update index.html with get in touch, address and map
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#3056 rate us hover colour to light colour #3055
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#3069 solved issue #3065
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#3070 corrected the alignment of subscribe button
  assets/css/style.css
Labels: level1, gssoc-ext, hacktoberfest-accepted

#3071 changed the color of icon
  assets/css/style.css
Labels: level1, gssoc-ext, hacktoberfest-accepted

#3076 I have improve a Rate us form with good UI and color combination of issue number #3039
  assets/css/rate.css
Labels: level1, gssoc-ext, hacktoberfest-accepted

#3077 To Adjust the address area in the contact page
  assets/css/style.css
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#3084 arrangement of navbar item in correct order
  Mystical-fantaies.html
  assets/html/ConnReader.html
  assets/html/about.html
  assets/html/about1.html
  assets/html/book_recommend.html
  assets/html/booklistswap.html
  assets/html/comsp.html
  assets/html/forgot-pass.html
  assets/html/freeBooks.html
  assets/html/index.html
  assets/html/login.html
  assets/html/mylogin.html
  assets/html/pricing.html
  assets/html/read_later.html
  biographies.html
  books.html
  chat.html
  comsp.html
  copyrightpolicy.html
  costefficient.html
  diverseLiteracy.html
  environmental-impact.html
  historical-chronicals.html
  index.html
  intriguing-mysteries.html
  lol.html
  mindful-living.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#3087 UPDATED CONTACT SECTION
  assets/css/style.css
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#3090 added card to all the book items in the literary realm subpages issue: #3051
  Mystical-fantaies.html
  assets/css/freeBooks.css
  assets/html/freeBooks.html
  biographies.html
  historical-chronicals.html
  intriguing-mysteries.html
  mindful-living.html
  romantic-esc.html
  scifi.html
  thrilling-adventures.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#3091 issue #3040 solved
  .vscode/settings.json
  index.html
Labels: level3, gssoc-ext, hacktoberfest-accepted

#3093 solved issue #3073
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#3095 solved issue #3092
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#3117 Fixed Bug
  assets/html/pricing.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#3118 unnecessary arrows were present are removed #2864
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#3113 footer enhacement #3108
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#3105 I've added html as well as css file for the quicklinks and some changes made.
  footer1.css
  footer1.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#3120 Icons on Home Page(left side-vertical)
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#3122 fixed overlaping elements in booklistswap
  assets/html/booklistswap.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#3126 Fix the issue of Nav_buttons link properly
  assets/html/event.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#3130 Changed Position of Profile Avatar
  assets/css/style.css
Labels: level1, gssoc-ext, hacktoberfest-accepted

#3131 Improved Contributing Section in Contributing.md
  CONTRIBUTING.md
Labels: level1, gssoc-ext, hacktoberfest-accepted

#3133 Fix dropdown button issue in Login Page
  assets/html/login.html
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#3135 fixed the more button in nav bar in login page
  assets/html/login.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#3137 Fix the Issues in footer Section
  assets/css/style.css
Labels: level1, gssoc-ext, hacktoberfest-accepted

#3139 Create signup1.html(Updated the Signup Page)
  signup1.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#3140 Update terms&cond.html 3068
  terms&cond.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#3144 Fix more Dropdown button in community page.
  comsp.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#3146 Fix Community Chat page navigation issue page not found.
  assets/html/about.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#3163 Fixes the Issues in Get In touch section
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#3173 Fix Rate Us Form Validation and Enhance CSS
  assets/css/rate.css
  assets/js/rate.js
  index.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#3175 Update CODE_OF_CONDUCT.md
  Information/CODE_OF_CONDUCT.md
Labels: level1, gssoc-ext, hacktoberfest-accepted

#3178 Fixed misalignment of Profile icon in Navbar issue ! #3150
  assets/css/style.css
Labels: level1, gssoc-ext, hacktoberfest-accepted

#3181 strong password check
  mylogin.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#3184 Improved the nav bar , profile icon , change theme button overflow fi…
  assets/css/style.css
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#3153 Updated login UI: changed button text and made layout single-page for…
  assets/css/login.css
  assets/html/login.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#3191 Added Table Of Contents to readme file
  README.md
Labels: level1, gssoc-ext, hacktoberfest-accepted

#3192 Fix the dropdown navigation link button issue
  assets/html/about.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#3194 successfully attached the footer section of the
  assets/html/profileedit.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#3201 updated
  index.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#3202 DOC: UPDATED README.md #3186
  README.md
  assets/hacktoberfest.png
  benefits.png
  genre.png
  home.png
Labels: level2, gssoc-ext, hacktoberfest-accepted

#3205 Fix Hover Color for Quick Links on Login/Signup Page
  assets/css/login.css
Labels: level1, gssoc-ext, hacktoberfest-accepted

#3206 Update audiobook.html
  audiobook.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#3208 solved #3172
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#3210 solved issue #3171
  index.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#3215 corrected the alignment
  index.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#3179 Added a Custom cursor effect in Website
  Mystical-fantaies.html
  assets/html/about.html
  costefficient.html
  diverseLiteracy.html
  e.html
  email.html
  environmental-impact.html
  footer1.html
  help.html
  historical-chronicals.html
  index.html
  lol.html
  mindful-living.html
  mylogin.html
  privacynotice.html
  profile.html
  scifi.html
  signup1.html
  terms&cond.html
  thrilling-adventures.html
Labels: level3, gssoc-ext, hacktoberfest-accepted

#3218 fixes: Login and Signup Buttons Misaligned – Font Size, Padding, and Margin Issues #3187
  assets/css/login.css
  assets/html/login.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#3219 Added new Feature
  connectWithsame.html
  index.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#3220 Fix the issue of header nav menu_bar button.
  index.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#3224 sucessfully added the footer section in my profile menu
  profile.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#3232 updated visibility of socials icons in dark mode
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#3234 Successfully attached an attractive footer section in the HELP CENTER menu
  help.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#3236 icons added
  index.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#3247 Fixed misalignment of Profile icon in Navbar issue ! #3243
  assets/css/style.css
  index.html
Labels: documentation, good first issue, level1, gssoc-ext, hacktoberfest-accepted

#3241 fixed the position of left and right buttons they are overlapping the…
  assets/css/litrary_realms.css
Labels: documentation, good first issue, level1, gssoc-ext, hacktoberfest-accepted

#3240 removed arrows
  index.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#3242 Updated cookie pop up
  cookiepolicy.html
  index.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#3245 Aligned all the pricing boxes as well as fixed the alignment..Gave some Hover effects to the cards and container.It's looking beautiful then the previous pricing chart.all the boxes have got equal spacing now..The responsiveness part of the boxes are really improvised than the previous boxes
  pricing.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#3248 Update privacynotice.html
  privacynotice.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#3250 Twitter icon
  assets/html/index.html
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#3251 Fixed misalignment of Dark mode button in Navbar ! #3244
  assets/css/style.css
Labels: level1, gssoc-ext, hacktoberfest-accepted

#3255 Fixed Unaligned Navbar
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#3258 fixed overlapping items
  assets/html/about.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#3259 Rate us container not going with the colour scheme of website
  assets/css/rate.css
Labels: level1, gssoc-ext, hacktoberfest-accepted

#3262 I updated our visions
  our-vision.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#3269 Update profile.css
  profile.css
Labels: level2, gssoc-ext, hacktoberfest-accepted

#3270 Successfully attched the footer section of the AUDIO BOOK menu
  audiobook.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#3271 BUG:Profile Icon and Mode Overlap
  assets/html/about.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#3272 Footer Section in Community Spotlight Redesigned Properly
  comsp.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#3276 text color changed appropriately acc to the theme
  assets/css/login.css
Labels: level2, gssoc-ext, hacktoberfest-accepted

#3280 Fixed Issue in Contact page ! #3254 #3257
  assets/css/style.css
  assets/html/about.html
  index.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#3282 Added New Feature
  index.html
  revitalize.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#3283 navbar updated
  assets/css/style.css
  index.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#3291 I have made changes in homepage texts of light modea
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#3292 upadte a stay connect page
  index.html
  stay_connect.css
Labels: level1, gssoc-ext, hacktoberfest-accepted

#3293 remove hover
  assets/css/style.css
Labels: level1, gssoc-ext, hacktoberfest-accepted

#3298 added top-down scroll bar
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#3299 added functionality and feature to contact us page
  contactus1.html
Labels: gssoc-ext, hacktoberfest-accepted

#3303 Fixed Bug #3301 and removed the thick 2 rem borders to 2px borders
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#3304 Cookie Consent Dialog Box Cross Icon Bug Solved !
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#3305 Fixed Login/SignUp page issue ! #3297
  assets/css/login.css
  assets/css/style.css
  assets/html/login.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#3309 fixes: Navbar Logo and Links Misalignment on the /audiobook Page #3295
  audiobook.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#3310 i have fixed the theme icon
  assets/html/about.html
  chat.css
Labels: level1, gssoc-ext, hacktoberfest-accepted

#3311 Fixed Login Page in Dark Mode.
  darkmode1.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#3312 fixes: Navbar Logo and Profile Icon Not Visible on /books Page #3300
  assets/css/style.css
  books.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#3319 Added a scroll down button
  index.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#3321 Fix the page not found error also fix some home section code issue.
  assets/html/login.html
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#3333 Fixes:#3332:BUG:In the footer section Copyright Policy,Vision,Privacy Policy links were not hovering
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#3345 fixed issue #3344 Footer in About us page
  assets/html/about.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#3334 Fixed Read Later page all issue ! #3330 #3327 #3329
  assets/css/read_later.css
  assets/html/about.html
  assets/html/index.html
  assets/html/read_later.html
  our-vision.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#3348 Successfully updated color theme according to the Web page
  assets/html/event.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#3354 Added Guidlines for Project Setup in Local Machine
  README.md
Labels: level2, gssoc-ext, hacktoberfest-accepted

#3357 Images are added in donate books section
  lib.jpg
  n.jpg
  sc.jpg
Labels: level1, gssoc-ext, hacktoberfest-accepted

#3360 Adding and design the Footer of About Us page also add function to subscribe the newsletter.
  assets/html/about.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#3326 Images in the donation section of the index.html file
  assets/html/index.html
  assets/images/images/lib.jpg
  assets/images/images/ngo.jpeg
  assets/images/images/sc.jpg
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#3341 #3286 Subscibe button modification
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#3363 fix: Validate Contact Us Name Field to Accept Only Letters
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#3365 fix: Validate Newsletter Form "Name" Field to Accept Only Letters
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#3367 fixFooter Newsletter Form - Name Field Validation
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#3369 Fix Header of About us page alignment issue
  assets/html/about.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#3373 Modified the transition effect for "Rate Us" section.
  index.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#3375 Adding and design Footer of Free E-Books page.
  assets/html/freeBooks.html
Labels: level1, gssoc-ext, hacktoberfest-accepted
